# docker单节点集群部署
# 参考:https://www.elastic.co/guide/en/elasticsearch/reference/7.11/docker.html

version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      - overlay

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.2
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]' # kibana默认值
    depends_on:
      - elasticsearch
    networks:
      - overlay

volumes:
  data01:


networks:
  overlay:
