# 注释
GET https://httpbin.org/get?name=frank&gender=male

###

POST https://httpbin.org/post
# Content-Type:客户端告诉服务器实际发送的数据类型
Content-Type: application/json  # 序列化后的JSON字符串类型

{
  "key1": 123,
  "key2": [
    234,
    456
  ]
}

###

POST https://httpbin.org/post
Content-Type: application/json

# 从文件中读取body
< test_data/tes0.json

###

POST http://127.0.0.1:5000/get_data
Content-Type: application/json

{
  "data": 123
}

###

POST http://127.0.0.1:5000/get_data
Content-Type: application/x-www-form-urlencoded  # 浏览器原生的form表单类型

{
  "data": 123
}